APP_NAME = "ProxyWright"
ORG_NAME = "Houtadono"
DB_PATH = "profiles.db"
DEFAULT_START_URL = "https://api.ipify.org/"
PROXY_TEST_URL = "https://api.ipify.org?format=json"
PROXY_TEST_TIMEOUT = 6
APP_VERSION = "1.0.0"
APP_UPDATE_URL = "https://api.github.com/repos/houtadono/houtadono/Proxy-Wright/releases"
SUPPORTED_BROWSERS = ["chromium"]
